name: e2eTest
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: "latest"

    - name: Install List Config Plugins
      run: npx -y list-config-plugins@latest -v

    - run: bun i --cwd=__tests__

    - run: bun test --cwd=__tests__
