name: Quality Checks CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 'latest'

    - name: Install dependencies
      run: bun install

    - name: Run typecheck
      run: bun run typecheck

    - name: Run lint
      run: bun run lint:CI

    - name: Run build
      run: bun run build

